# Generated by Django 3.1.7 on 2021-03-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_auto_20210309_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
