# Generated by Django 3.1.7 on 2021-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infoapp', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_name', models.CharField(max_length=100)),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('mobile_no', models.TextField()),
            ],
        ),
    ]
