# Generated by Django 3.1.7 on 2021-03-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0005_auto_20210309_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
