# Generated by Django 3.1.7 on 2021-03-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0006_managementinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsinfo',
            name='m_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infoapp.managementinfo'),
            preserve_default=False,
        ),
    ]
